# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]
    name: Building using Dotnet ${{ matrix.dotnet }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Copy to server
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          # Path to the local folder you want to copy.
          local: ./
          # Path on the remote server to copy to.
          remote: ~/temp
          host: ${{ secrets.HOST_IP }}
          # Username for authentication.
          username: ${{ secrets.USER_NAME }}
          # Password for password-based user authentication.
          password: ${{ secrets.PASSWORD }}
    
